* Beyond code

<Missed the very start, possibly some important context not here>
** Code Complexity
It's not just a one dimensional attribute. We can represent complexity with increasing circles.
But there's also the frequency of code changes. This can be represented as different colours.
** We can use a tool to identify where code is complex and not.
So visually we can see in the code where is complex, and where changes often.
** Your code as a crime scene was a previous book written
*** But decided to write it in clojure because it's fun. And fun is important!
** Evolutionary metrics
So we have metrics of the code with analysis using
*** parsing => aggregation -> analysis => output (-> csv)
<Where fat arrow represents coming from multiple sets being processed before the next step>
** So doing it in Clojure he decided to use instaparser.
Pros: It's as easy as regex. Cons: It's as easy as regex.

But really, it can be represented as a simple CFG each using various regex syntax.

** But parsing large datasets is ridiculously slow.
*** Very memory hungry
*** so instead of parsing everything -> just lazily parse little bits at a time. A form of tokenization/chunking.
*** This is very effective. Do chunking.
** One interesting thing to look at is the trueism "Code doesn't lie"
*** which is nice, but isn't necessarily the entire truth
*** An example of which is temporal coupling.
Change two files in a commit, change something else, change the original two.
**** So like traditional ideas of coupling. Physcial coupling when it points directly at something. Logical coupling when something relies on something else from a point in the program logic, if not explicit.
**** Temporal coupling can see a few examples of this being detected. <How come? I don't think temporal coupling is explained well enough yet>
** Analysing architectures
*** Microservices
**** idea is that we have a bunch of small services completely independent of each other, and a larger application using these libraries individually.
**** but in reality, there'll be some coupling between some client libs, shared db utils, communication libs, service templates (!)
** Code churn 
How much code changes over time.
*** So this is a possible output from the analysis
*** And we can analyse it using CSV
** Incanter for code viz
*** you can see code churn over time
This is basically just time series plotting, it seems.
** But this is all very well, and simple to see, but it's really boring.
Time to use processing to make programming fun again. Fuck all the best practices!
*** So started to use processing to investigate stuff
But soon started to find it's very difficult to maintain this code.
*** Clojure to the rescue!
Quil.
*** Quil
**** One thing that we now have, is fun mode.
This is turns the programming model much more functional — so functions return a new world, etc.
However, there's still a lot of code
*** The more programmers on one piece of code, the more problems with it.
Maybe it's because the more parallel programming on a piece of code, the worst the bugs.
**** We can use Quil to analyse this exact problem. We can check how much contributors vs number of bugs.
One interesting view is the clojure fractal figures. A library with a big amount of code written by one person with a lots of small patches by other people is generally regarded as better safe.
But if you see lots of colours in your fractral [seems to be similar to grand-perspective/baobab style fractrals]


* Adam Tornhill
recommends zoochurn, and code maat.
@adamtornhill
[[the-living-code.com]]
